### ISSUE TITLE
options.entry is deprecated, use options.input

### ISSUE THREAD

**Issue by alexandr-shikin** [KordonBleu/enslavism#2]
**1) node bundler.js** return to cmd:
>>options.entry is deprecated, use options.input
>>The following options have been renamed - please update your config: dest -> file
>>Enslavism bundle generated

**2) node master.js
3) node slave.js
4) open page on browser** ( I see true page ), but **cmd with master.js** return:
>>options.entry is deprecated, use options.input
>>The following options have been renamed - moduleName -> name
>>Client connected @ ::1

**Comment by getkey** [comment]
Seems related to this rollup/rollup#1479.

I am not actively maintaining this project anymore but if you can, I gladly accept pull requests. :-)
Fixing it should be straightforward, it's just a matter of changing a few property names, as described in rollup/rollup#1479.
