### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by therealmikz** [KordonBleu/enslavism#3]
I'm using `node` docker image with following node and npm versions:

node@e64ba5e5c5ee:/app$ node -v
v12.2.0
node@e64ba5e5c5ee:/app$ npm -v
6.9.0

Whole build log is attached to this issue.

[output.txt](https://github.com/KordonBleu/enslavism/files/3167215/output.txt)

**Comment by getkey** [comment]
Hey @therealmikz, I am no longer actively maintaining this project. It uses old NPM modules than do not support newer versions of Node.js.

If you submit a PR with the updated dependencies, I'd gladly accept it. :wink: (please use Yarn as the package manager)

**Comment by therealmikz** [comment]
I'd be grateful if you could give me a hint (of course if you have a little spare time) on which node version it actually works so I can try to make something of it.

**Comment by getkey** [comment]
Sure thing! The last version of Node.js I ran this on was 7. Version 6 should work as well.

**Comment by dill0wn** [comment]
This will basically be a worthless comment, but I just wanted to say: I haven't used your framework yet, but it is very cool and fills a niche that I am looking for. I was thinking about building something similar and it is very wonderful to see that I am not alone!

Now that iOS supports WebRTC it feels like the time is right for making interesting realtime collaborative applications that everyone could use.

**Comment by willstott101** [comment]
#4 Is working on latest LTS node (12.16) for me

**Comment by getkey** [comment]
Fixed in #4 and published on NPM as v0.9.0 so I'm closing this issue. :slightly_smiling_face:
